[project]
name = "mcp-python-server"
version = "0.1.0"
description = "MCP servers for learning Model Context Protocol"
requires-python = ">=3.10"
dependencies = [
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.6",
    "langchain[mcp]>=1.4.2",
    "langgraph>=1.2.12",
    "mcp[cli]>=2.0.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[tool.uv]
package = false
